export const metadata = {
  title: "Подвійні пам`ятники",
  description: "Generated by create next app",
};

const DoubleMonuments = () => {
  return <h2>подвійні</h2>;
};

export default DoubleMonuments;
