import Description from "@/components/Description/Description";

export const metadata = {
  title: "Каталог пам`ятників",
  description: "Generated by create next app",
};
const Catalog = () => {
  return <Description />;
};

export default Catalog;
