export const metadata = {
  title: "Аксесуари до пам`ятника",
  description: "Generated by create next app",
};

const MonumentAccessories = () => {
  return <h2>аксесуари</h2>;
};

export default MonumentAccessories;
